[[flash]]
address = 0x00000000
size = 393216
read = true
write = true
execute = true

[[ram]]
address = 0x60000
size = 131072
read = true
write = true
execute = true

[[sboot_hdr]]
address = 0x400
size = 32
read = true
write = false
execute = false

