# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2024 Advanced Micro Devices, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name = "ast1060-ecdsa-test"
target = "thumbv7em-none-eabihf"
board = "ast1060-rot"
chip = "../../chips/ast1060"
stacksize = 1024 

[kernel]
name = "ast1060-ecdsa-test"
requires = {flash = 32000, ram = 4096}

[tasks.jefe]
name = "task-jefe"
priority = 0
max-sizes = {flash = 8192, ram = 4096}
start = true
stacksize = 1536
notifications = ["fault", "timer"]

[tasks.idle]
name = "task-idle"
priority = 5
max-sizes = {flash = 128, ram = 256}
stacksize = 256
start = true

[tasks.uart_driver]
name = "drv-ast1060-uart"
priority = 2
max-sizes = {flash = 8192, ram = 2048}
uses = ["uart"]
start = true
notifications = ["uart-irq"]
interrupts = {"uart.irq" = "uart-irq"}

[tasks.ecdsa_server]
name = "drv-openprot-ecdsa-server"
priority = 3
max-sizes = {flash = 16384, ram = 4096}
start = true
stacksize = 2048

[tasks.ecdsa_test]
name = "task-ecdsa-test"
priority = 4
max-sizes = {flash = 16384, ram = 4096}
start = true
stacksize = 2048
task-slots = ["ecdsa_server", "uart_driver"]